### PR TITLE
Adding security features into main (flask-login, sqlalchemy, wtforms)

### PR DESCRIPTION
**Pull request by Roy-Lam**

### CODE REVIEW

**Comment by bc163836** [comment]
- Chatroom-m Doesnt Work (Form error)
- Once Message is sent to user, Refreshing page deletes history of messages

**Comment by Roy-Lam** [comment]
- mobile version of chatroom is broken

- the inaccessible for messaging bar and send message button is gone/not functional

**Comment by CelynChew** [comment]
looks good. but just double check the routes to make sure that the right templates are rendered.

**Review by CelynChew — APPROVED** [review]
looks good. but just double check the routes to make sure that the right templates are rendered before merging

**Pull request merged**
